---
title: "HW2"
author: "Chanukya"
date: "10/9/2019"
output: html_document
---

```{r}
data  <- read.csv("/Users/chanukya/Documents/GitHub/DataMining/HW2/leaf/leaf.csv")
#View(data)
#Aspect ratio , Elongation and Solidity
#changing column names
column_names <- c("Class","SpecimenNumber","Eccentricity","AspectRatio","Elongation","Solidity","StochasticConvexity","IsoperimetricFactor","MaximalIndentationDepth","Lobedness","AvgIntensity","AvgContrast","Smoothness","ThirdMoment","Uniformity","Entropy")
for(i in 1:length(column_names)){
  names(data)[i]<- column_names[i]
}
colnames(data)

```

```{r}
#b)

problem_a_columns <- c("AspectRatio","Elongation","Solidity")
data <- data.frame(scale(data))
#par( mfrow = c( 1, 3 ) )
for(i in 1:length(problem_a_columns)){
  boxplot(data[problem_a_columns[i]], main =  problem_a_columns[i])
}
```




```{r}
# c)
data1 <- data
outliers_aspect <- boxplot(data1$AspectRatio, plot = FALSE)$out
#here are the outliers
outliers_aspect
data1 <- data1[which(data1$AspectRatio %in% outliers_aspect),]
boxplot(data1$AspectRatio)

data1 <- data
outliers_elongation <- boxplot(data1$Elongation, plot = FALSE)$out
outliers_elongation
# no outliers 
data1 <- data1[which(data1$Elongation %in% outliers_elongation),]
boxplot(data$Elongation)
# no errors in elongation 

#POPULATION PARAMETER CALCULATIONS
data1 <- data
outliers_solidity <- boxplot(data1$Solidity, plot = FALSE)$out
# outliers in solidity
outliers_solidity
data1 <- data1[which(data1$Solidity %in% outliers_solidity),]
boxplot(data1$Solidity)

```



```{r}
#f)
Accu1<-0.6410256
Accu2<-0.4871795 
n<-length(data1)
d<-Accu1-Accu2
sigma1= Accu1*(1-Accu1)/n
sigma2<-Accu2*(1-Accu2)/n
sigmat<-sqrt(sigma1+sigma2)

Z<-2.33 #confidence level 98%
dt1<-d+(Z*sigmat)
dt2<-d-(Z*sigmat)
dt<-c(dt2,dt1)
#confidence Interval
print(dt)

# since 0 is in the confidence intervals we can say models are statistically insignificant.
```


```{r}
#g)
data1 <- data
in_train <- sample(nrow(data1))
data1 <- data1[in_train,]
train_data <- data1[1:300,]
test_data  <- data1[301:nrow(data1),]
library(C50)

train_data$Class <- as.factor(train_data$Class)
vars = c("SpecimenNumber","Eccentricity","AspectRatio","Elongation","Solidity","StochasticConvexity","IsoperimetricFactor","MaximalIndentationDepth","Lobedness","AvgIntensity","AvgContrast","Smoothness","ThirdMoment","Uniformity","Entropy")
tree_mod <- C5.0(x = train_data[, vars], y = train_data$Class)
test1 <- function(a,b){
  predicted <- predict(a,b)
  return(predicted)
}

#input<- data.frame(19,0.451,2.700,0.5169,0.6800,0.8421,0.609,0.02530,0.1100,0.007984,0.042948,0.0050183,0.00071981,2.7289e-05,0.42553)
input <- data1[1, vars]
predicted <- test1(tree_mod,input)
predicted

input <- data1[5, vars]
predicted <- test1(tree_mod,input)
predicted

input <- data1[7, vars]
predicted <- test1(tree_mod,input)
predicted





```